---
title: "data_prep"
author: "Laura García Romañach"
date: "2024-10-30"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(data.table)
library(plotrix)
```

```{r load expression data}
load("/Users/laia0002/aspen-FT-compendium/data/gene-counts-and-VSTexpression.RData")
load("/Users/laia0002/aspen-FT-compendium/RData/genetable_1_3_2_year_around.RData")
data <- data[rowSums(data) > 0, ]

cat("Genes x Samples: ", paste0(dim(data), collapse = " x "))
cat("Genes x Samples: ", paste0(dim(data), collapse = " x "))

subannot <- subannot %>% 
  separate(Module, c('Module_color', 'Module'), sep = "/")

subannot[subannot==""]<-NA

#Arrange dataset for POPUL-R

samples.sep <- samples.sep %>% 
  unite("Treatment_Week", Treatment, Week, na.rm = TRUE, sep = "") 

samples.sep$Treatment_Week <- if_else(samples.sep$Location == "Greenhouse" , samples.sep$Treatment_Week, "")

samples.sep <- samples.sep %>% 
  unite("Month/Treatment", Month, Treatment_Week, na.rm = TRUE, sep = "")

samples.sep$`Month/Treatment` <- if_else(samples.sep$`Month/Treatment` == "LD1" , "BB1",
                                         if_else(samples.sep$`Month/Treatment` == "LD2" , "BB2",
                                                 if_else(samples.sep$`Month/Treatment` == "LD3" , "BB3",
                                                         if_else(samples.sep$`Month/Treatment` == "LD4" , "LD", samples.sep$`Month/Treatment`))))

treatment_mapping <- c(
  "SEP", "OCT", "DEC", "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL",
  "AUG", "SD15", "CT2", "CT8", "CT10", "BB1", "BB2", "BB3", "LD", "SD1", 
  "SD2", "SD3", "SD10"
)

samples.sep$Treatment2 <- match(samples.sep$`Month/Treatment`, treatment_mapping)

samples.sep$Location <- factor(samples.sep$Location,
                               levels = c("Outdoor", 
                                          "Greenhouse"),
                               labels = c("Outdoor",
                                          "Indoor"))

samples.sep <- samples.sep %>%
  arrange(desc(Location), Tissue) %>% 
  arrange(Treatment2)

expression_data <- data %>% 
  as.data.frame() %>% 
  rownames_to_column(var = "Gene") %>% 
  pivot_longer(!Gene, names_to = "Samples", values_to = "Expression") %>% 
  mutate(Sample = factor(Samples, levels = colnames(data))) %>% 
  left_join(samples.sep %>% dplyr::select(-Expression), by = "Samples") %>% 
  arrange(Treatment2)

expression_data_subannot <- expression_data %>% 
  left_join(subannot, by = c("Gene" = "Gene name"))


expression_data_subannot <- expression_data_subannot %>% 
  group_by(Gene, `Month/Treatment`, Location, Tissue, Treatment2, Family) %>%
      summarize(mean = mean(Expression),
                se = std.error(Expression)) %>%
      arrange(Treatment2) %>% 
  as.data.table()

expression_data_subannot$`Month/Treatment` <- factor(expression_data_subannot$`Month/Treatment`, levels = c(
                                                              "SEP",
                                                              "OCT",
                                                              "DEC",
                                                              "JAN",
                                                              "FEB",
                                                              "MAR",
                                                              "APR",
                                                              "MAY",
                                                              "JUN",
                                                              "JUL",
                                                              "AUG",
                                                              "SD15","CT2","CT8","CT10",
                                                              "BB1","BB2","BB3", "LD",
                                                              "SD1","SD2","SD3","SD10"))



# #=====For mini version====#
# 
# GOIs_paper <- read_delim("/Users/laia0002/POPUL_R_mini/GOI_mini_app.txt", col_names = FALSE) %>%
#   dplyr:::select(X2)
# 
# colnames(GOIs_paper) <- "Gene name"
# 
# TFs <- subannot %>%
#   filter(`Gene name` %in% GOIs_paper$`Gene name`) %>%
#   select(Family) %>%
#   unique() %>%
#   drop_na()
# 
# expression_data_subannot_mini <- GOIs_paper %>%
#   left_join(expression_data_subannot, by = c("Gene name" = "Gene"))
# 
# expression_data_subannot_mini <- expression_data_subannot %>%
#   filter(Gene %in% nodes_mini$`Gene name`)
# nodes_mini$`Gene name` %>%
# left_join(expression_data_subannot, by = c("Gene name" = "Gene"))
# 
# colnames(expression_data_subannot_mini)[1] <- "Gene"
# 
# saveRDS(expression_data_subannot_mini, "/Users/laia0002/POPUL_R_mini/expression_data/expression_data_mini.rds")
# 
# annot_col <- readRDS("/Users/laia0002/POPUL_R_mini/annot_col.rds")
# 
# annot_col$`Month/Treatment` <- if_else(annot_col$`Month/Treatment` == "LD1" , "BB1",
#                                          if_else(annot_col$`Month/Treatment` == "LD2" , "BB2",
#                                                  if_else(annot_col$`Month/Treatment` == "LD3" , "BB3",
#                                                          if_else(annot_col$`Month/Treatment` == "LD4" , "LD", annot_col$`Month/Treatment`))))
# 
# saveRDS(annot_col, "/Users/laia0002/POPUL_R_mini/annot_col.rds")

#==========#

#For complete version
saveRDS(expression_data_subannot,
        "/Users/laia0002/POPUL_R/expression_data/expression_data.rds")

annot_col <- readRDS("/Users/laia0002/POPUL_R_mini/annot_col.rds")

 annot_col$`Month/Treatment` <- factor(annot_col$`Month/Treatment`, 
                                             levels = c("SEP", "OCT", "DEC", "JAN", "FEB", "MAR", 
                                                        "APR", "MAY", "JUN", "JUL", "AUG", 
                                                        "SD15", "CT2", "CT8", "CT10", "BB1", 
                                                        "BB2", "BB3", "LD", "SD1", "SD2", 
                                                        "SD3", "SD10"))
saveRDS(annot_col, "/Users/laia0002/POPUL_R/annot_col.rds")

#============#
```

```{r load network}
# #Load thresholded network
# nodes <- data.frame(read_delim(paste0("/Users/laia0002/POPUL_R_extrafiles/nodes-all_1_3_2_year_around_v2_0.1.txt.gz")))
# edges <- data.frame(read_delim(paste0("/Users/laia0002/POPUL_R_extrafiles/edges-all_1_3_2_year_around_v2_0.1.txt.gz")))

#=====For mini version=====#

# # nodes_subannot <- readRDS("/Users/laia0002/POPUL_R/nodes_subannot.rds")
# 
# nodes_subannot <- nodes %>% 
#   select(nodeName) %>% 
#   left_join(subannot, by = c("nodeName" = "Gene name")) %>% 
#   select(!c(GOI, Module_color)) %>% 
#   rename(c(`Gene name` = nodeName, `GO term`= GO))
# 
# # nodes_mini <- GOIs_paper %>%
# #    left_join(nodes_subannot)
# 
# # first_neigh_mini <- edges %>%
# #   dplyr::select(fromNode, toNode, weight) %>%
# #   filter(fromNode %in% GOIs_paper$`Gene name` | toNode %in% GOIs_paper$`Gene name`) %>%
# #   filter(weight >= 0.3)
# # 
# # nodes_mini <- nodes_subannot %>%
# #   filter(`Gene name` %in% unique(c(first_neigh_mini$fromNode, first_neigh_mini$toNode)))
# 
# 
# 
# # first_neigh_nodes_mini <- unique(c(first_neigh_mini$fromNode, first_neigh_mini$toNode))
# 
# #
# # first_neigh_edges_mini <- edges %>%
# #   dplyr::select(fromNode, toNode, weight) %>%
# #   filter(fromNode %in% c & toNode %in% c) %>%
# #   filter(weight >= 0.3)
# #
# # first_neigh_all_mini <- rbind(first_neigh_mini, first_neigh_edges_mini)
# 
# # edges_mini <- edges %>%
# #   dplyr::select(fromNode, toNode, weight) %>%
# #   filter(fromNode %in% nodes_mini$`Gene name` & toNode %in% nodes_mini$`Gene name`) %>%
# #   filter(weight >= 0.3)
# # nodes_mini <- nodes_mini %>% 
# #   select(!`GO term`)
# 
# # write.csv(first_neigh_edges_mini, gzfile("/Users/laia0002/POPUL_R_mini/network/edges_mini.csv.gz"), row.names = FALSE)
# # saveRDS(nodes_mini, gzfile("/Users/laia0002/POPUL_R_mini/network/nodes_mini.rds"))
# saveRDS(edges_mini, gzfile("/Users/laia0002/POPUL_R_mini/network/edges_mini.rds"))
#==========================#


```

```{r load network and modules}
# #=== For mini version===#
# 
# load("/Users/laia0002/aspen-FT-compendium/RData/GO_modules_1_3_2_year_around.RData")
# 
# module_color <- setNames(unique(subannot$Module), unique(subannot$Module_color))
# index <- setNames(unique(subannot$Module), unique(subannot$Module_color))
# names(GO_modules) <- module_color[names(GO_modules)]
# 
# #Remove module trash grey and brown4/46, 46 has no GO terms
# 
# GO_modules <- GO_modules[c(2:45, 47)]
# sort(names(GO_modules))
# 
# GO_modules_df <- do.call(rbind, lapply(names(GO_modules), function(name) {
#       cbind(Module = name, GO_modules[[name]])
#     })) 
# 
# # get_module <- function (number) {
# #  GO_modules[[number]]
# # }
# 
# 
# # saveRDS(GO_modules_df, "/Users/laia0002/POPUL_R/GO_modules.rds")
# 
# # GO_modules <- readRDS("/Users/laia0002/POPUL_R/GO_modules.rds")
# 
# #Only save necessary modules in mini
# # modules_mini <- filter(subannot, `Gene name` %in% GOIs_paper$`Gene name`) %>% 
# #   select(Module) %>% 
# #   unique()
# # nodes_mini <- readRDS("/Users/laia0002/POPUL_R_mini/network/nodes_mini.rds")
# modules_mini <- filter(subannot, `Gene name` %in% nodes_mini$`Gene name`) %>% 
#   select(Module) %>% 
#   unique()
# 
# GO_modules_mini <- filter(GO_modules_df, Module %in% modules_mini$Module)
# 
# #Replace GO terms for GO IDs
# 
# # Step 1: Split concatenated GO terms in `nodes_mini` into separate rows
# nodes_expanded <- nodes_mini %>%
#   separate_rows(`GO term`, sep = ";\\s*")  # Split by "; " or ";" with spaces
# 
# # Step 2: Join with `GO_modules_df` to map GO terms to GO IDs
# nodes_with_ids <- nodes_expanded %>%
#   left_join(GO_modules_df %>% select(`GO term`, `GO id`), by = "GO term") %>% 
#   # filter(!is.na(`GO id`)) %>% 
#   unique() 
# #Warning will appear, relationship many to many is okay because I am putting all GO terms per gene
# 
# # Step 3: Re-concatenate GO IDs by grouping back to original rows
# nodes_reformatted <- nodes_with_ids %>%
#     group_by(`Gene name`, Description, ATG, `ATG symbol`, `ATG full name`, Family, Centrality, Module) %>% 
#     summarise (`GO id` = paste(`GO id`, collapse = "; "),
#                `GO term` = paste(`GO term`, collapse = "; "))
# 
# nodes_reformatted$`GO id` <- ifelse(nodes_reformatted$`GO id` == "NA", NA, nodes_reformatted$`GO id`)
# 
# saveRDS(nodes_reformatted, "/Users/laia0002/POPUL_R_mini/network/nodes_mini.rds")
# 
# GO_modules_mini$`P-value` <- as.numeric(GO_modules_mini$`P-value`)
# saveRDS(GO_modules_mini, "/Users/laia0002/POPUL_R_mini/GO_modules_mini.rds")

#====================#

#For big version
nodes <- data.frame(read_delim(paste0("/Users/laia0002/POPUL_R_extrafiles/nodes-all_1_3_2_year_around_v2_0.1.txt.gz")))
edges <- data.frame(read_delim(paste0("/Users/laia0002/POPUL_R_extrafiles/edges-all_1_3_2_year_around_v2_0.1.txt.gz")))

edges <- edges %>%
  dplyr::select(fromNode, toNode, weight)

edges_dt <- as.data.table(edges)
setkey(edges_dt, fromNode, toNode)

nodes_subannot <- nodes %>% 
  select(nodeName) %>% 
  left_join(subannot, by = c("nodeName" = "Gene name")) %>% 
  select(!c(GOI, Module_color)) %>% 
  rename(c(`Gene name` = nodeName, `GO term`= GO))

load("/Users/laia0002/aspen-FT-compendium/RData/GO_modules_1_3_2_year_around.RData")

module_color <- setNames(unique(subannot$Module), unique(subannot$Module_color))
index <- setNames(unique(subannot$Module), unique(subannot$Module_color))
names(GO_modules) <- module_color[names(GO_modules)]

#Remove module trash grey(position 1) and brown4/46, 46 has no GO terms. Add empty df instead

GO_modules <- GO_modules[c(2:47)]
GO_modules[["46"]] <- data.frame(`GO id` = NA,
                                 `P-value` = NA,
                                 x = NA,
                                 n = NA,
                                 `GO term` = NA,
                                 check.names = FALSE)
sort(names(GO_modules))

GO_modules_df <- do.call(rbind, lapply(names(GO_modules), function(name) {
      cbind(Module = name, GO_modules[[name]])
    }))

GO_modules_df$`P-value` <- as.numeric(GO_modules_df$`P-value`)
GO_modules_df[is.na(GO_modules_df)] <- 0
GO_modules_df <- data.table(GO_modules_df)

  
saveRDS(GO_modules_df, "/Users/laia0002/POPUL_R/GO_modules.rds")

nodes_expanded <- nodes_subannot %>%
  separate_rows(`GO term`, sep = ";\\s*")  

nodes_with_ids <- nodes_expanded %>%
  left_join(GO_modules_df %>% select(`GO term`, `GO id`), by = "GO term") %>% 
  # filter(!is.na(`GO id`)) %>% 
  unique() 
#Warning will appear, relationship many to many is okay because I am putting all GO terms per gene

nodes_reformatted <- nodes_with_ids %>%
    group_by(`Gene name`, Description, ATG, `ATG symbol`, `ATG full name`, Family, Centrality, Module) %>% 
    summarise (`GO id` = paste(`GO id`, collapse = "; "),
               `GO term` = paste(`GO term`, collapse = "; "))

nodes_reformatted$`GO id` <- ifelse(nodes_reformatted$`GO id` == "NA", NA, nodes_reformatted$`GO id`)
nodes_reformatted <- data.table(nodes_reformatted)

saveRDS(nodes_reformatted, "/Users/laia0002/POPUL_R/network/nodes.rds")

saveRDS(edges_dt, gzfile("/Users/laia0002/POPUL_R/network/edges.rds"))

#===================#

# #Need to regenerate heatmaps of module eigengenes
# 
# #Rename heatmaps
# heatmaps_dir <- "/Users/laia0002/heatmaps_age"
# 
# # List of heatmap files
# heatmap_files <- list.files(heatmaps_dir, pattern = "heatmap_module_.*\\.pdf$", full.names = TRUE)
# 
# for (file in heatmap_files) {
#   # Extract the filename without the path
#   
#   # file <- "/Users/laia0002/heatmaps/heatmap_module_yellow.pdf" 
#   file_name <- basename(file)
#   
#   # Extract the color name between "_" and ".pdf"
#   color_name <- sub("heatmap_module_(.*)\\.pdf", "\\1", file_name)
#   
#   # Look up the number corresponding to the color name in the index
#   if (color_name %in% names(index)) {
#     color_number <- index[color_name]
#     
#     # Replace the color name with the number in the filename
#     new_name <- sub(color_name, color_number, file_name)
#     
#     # Generate full path for the new file name
#     new_file <- file.path(heatmaps_dir, new_name)
#     
#     # Rename the file
#     file.rename(file, new_file)
#     
#     cat("Renamed:", file_name, "to", new_name, "\n")
#   } else {
#     cat("No matching color found for:", file_name, "\n")
#   }
# }


```

